### PR TITLE
LPS-152516 Groovy Script Language fields are being replaced at source view by 'g' when definition is updated

### PR DESCRIPTION
**Pull request by RenanUmV**
Issue: [LPS-152516](https://issues.liferay.com/browse/LPS-152516)

### CODE REVIEW

**Comment by RenanUmV** [comment]
ci:test:sf

**Comment by RenanUmV** [comment]
ci:test:relevant

**Comment by naraandrade** [comment]
Just started reviewing :)

**Review by naraandrade — APPROVED** [review]

**Comment by naraandrade** [comment]
ci:forward

**Pull request closed without merging**
