### PR TITLE
LPS-147482 Collision warning (red border) is kept when node leaves diagram builder while colliding

### PR DESCRIPTION
**Pull request by michaelmdelcavalcanti**
[LPS-147482](https://issues.liferay.com/browse/LPS-147482)

### CODE REVIEW

**Comment by michaelmdelcavalcanti** [comment]
ci:test:sf

**Comment by michaelmdelcavalcanti** [comment]
ci:test:sf

**Comment by michaelmdelcavalcanti** [comment]
ci:test:relevant

**Comment by naraandrade** [comment]
Just started reviewing :)

**Review by naraandrade — CHANGES_REQUESTED** [review]
Hi @michaelmdelcavalcanti, your solution fixes the bug, but it introduces a side effect that can be annoying and that will happen more often than the bug we're trying to fix (when hovering the nodes with a node dragged from the sidebar, the nodes start "glitching", with the red border appearing and disappearing within seconds).

I think a better way to solve it would be calling the `onDragLeave` inside the `BaseNode`, in the `div` that has the `className=node-handle-area`. It will solve the problem for most of the cases without the side effect. Of course, it would be ideal to solve the problem for all cases, but this is already a bug that is not that common to happen, so turning it into a even more rare bug would be enough :)

**Comment by michaelmdelcavalcanti** [comment]
ci:test:sf

**Comment by naraandrade** [comment]
Just started reviewing :)

**Comment by naraandrade** [comment]
ci:test:relevant

**Comment by michaelmdelcavalcanti** [comment]
@naraandrade, when checking the test  [LocalFile.PortalSmokeUpgrade#ViewPortalSmokeArchive7413](https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/131326//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_PortalSmokeUpgrade_ViewPortalSmokeArchive7413_). 

The resulting error was: 
[exec] com.liferay.poshi.runner.PoshiRunner > test[LocalFile.PortalSmokeUpgrade#ViewPortalSmokeArchive7413] STANDARD_ERROR
[exec]     com.liferay.poshi.runner.exception.ElementNotFoundPoshiRunnerException: Element is not present at "//div[contains(@id,'navbar')]/ul/li/a[normalize-space()='Web Content']".

I believe it has no connection with the correction performed in this PR.

**Comment by naraandrade** [comment]
ci:test:relevant

**Comment by naraandrade** [comment]
ci:forward

**Pull request closed without merging**
