### PR TITLE
LPS-139408 Language dropdown menu opens in wrong position when editing a picklist item

### PR DESCRIPTION
**Pull request by GabrielHenriquedev**

### CODE REVIEW

**Comment by GabrielHenriquedev** [comment]
ci:test:sf

**Comment by GabrielHenriquedev** [comment]
ci:test:relevant

**Comment by samuelromeiro** [comment]
This PR has to be send for the Front-End Infra team to review.

**Comment by danvb112** [comment]
@GabrielHenriquedev and @samuelromeiro, I will close this PR, as it has to be sent to the Front-end infrastructure to be reviewed

**Pull request closed without merging**
