### PR TITLE
LPS-152309 Setting minimum field group size

### PR DESCRIPTION
**Pull request by lazhcsilva**

### CODE REVIEW

**Comment by lazhcsilva** [comment]
ci:test:sf

**Comment by lazhcsilva** [comment]
ci:test:relevant

**Comment by lazhcsilva** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
Hi, @lazhcsilva. I'll talk to our designer to check if this behavior really must be implemented. Besides, I've tested the PR and  unfortunately  this solution breaks the drag and drop as we can see bellow:

https://user-images.githubusercontent.com/26491796/183456795-9d67d7d6-dd44-4b45-a23e-ab1c70adc26f.mp4

**Comment by alinedoleron** [comment]
Hi @lazhcsilva, I discussed to the team and this ticket is not considered as a bug. I'll comment and close the ticket. Thanks for you effort on this case.

**Pull request closed without merging**
