### PR TITLE
LPS-145399 - When an invalid content is imported and corrected the error message still being displayed

### PR DESCRIPTION
**Pull request by fabiocampelo07**

### CODE REVIEW

**Comment by fabiocampelo07** [comment]
ci:test:relevant

**Comment by fabiocampelo07** [comment]
ci:test:relevant

**Comment by fabiocampelo07** [comment]
ci:test:sf

**Comment by fabiocampelo07** [comment]
ci:test:relevant

**Comment by fabiocampelo07** [comment]
ci:test:relevant

**Comment by fabiocampelo07** [comment]
ci:test:relevant

**Comment by naraandrade** [comment]
Just started reviewing :)

**Review by naraandrade — APPROVED** [review]

**Comment by naraandrade** [comment]
ci:forward

**Pull request closed without merging**
