### PR TITLE
LPS-152500 - Fixed spaces between single selection options

### PR DESCRIPTION
**Pull request by thiago-buarqque**
Related to issue: https://issues.liferay.com/browse/LPS-152500

### CODE REVIEW

**Comment by thiago-buarqque** [comment]
ci:test:sf

**Comment by thiago-buarqque** [comment]
ci:test:sf

**Comment by thiago-buarqque** [comment]
ci:test:relevant

**Comment by thiago-buarqque** [comment]
ci:test:relevant

**Comment by thiago-buarqque** [comment]
ci:test:relevant

**Review by alinedoleron — APPROVED** [review]

**Comment by alinedoleron** [comment]
ci:forward

**Pull request closed without merging**
