### PR TITLE
LPS-147415 add assignment by userId and screenName

### PR DESCRIPTION
**Pull request by HenriquePereiraa**

### CODE REVIEW

**Comment by HenriquePereiraa** [comment]
ci:test:sf

**Comment by HenriquePereiraa** [comment]
ci:test:relevant

**Comment by HenriquePereiraa** [comment]
ci:test:relevant

**Comment by anabuchmann** [comment]
Just started reviewing :)

**Comment by HenriquePereiraa** [comment]
ci:test:relevant

**Pull request closed without merging**
