### PR TITLE
LPS-155453 Insert Placeholder in input area inside form

### PR DESCRIPTION
**Pull request by rafaelpdemelo**
Description: I insert a placeholder in the input area inside the form and create a new language key it
link LPS: https://issues.liferay.com/browse/LPS-155453

### CODE REVIEW

**Comment by rafaelpdemelo** [comment]
ci:test:sf

**Comment by rafaelpdemelo** [comment]
ci:test:relevant

**Review by danvb112 — APPROVED** [review]
LGTM! :tada:

**Comment by danvb112** [comment]
ci:forward

**Comment by danvb112** [comment]
ci:forward

**Pull request closed without merging**
