### PR TITLE
LPS-148869 - Fix margin between buttom and label

### PR DESCRIPTION
**Pull request by lazhcsilva**

### CODE REVIEW

**Comment by lazhcsilva** [comment]
ci:test:sf

**Comment by lazhcsilva** [comment]
ci:test:sf

**Comment by lazhcsilva** [comment]
ci:test:relevant

**Comment by lazhcsilva** [comment]
ci:test:relevant

**Comment by MariMalta** [comment]
Just started reviewing :)

**Review by MariMalta — APPROVED** [review]

**Comment by MariMalta** [comment]
ci:forward

**Pull request closed without merging**
