### PR TITLE
LPS-101958 Required field asterisk for data definitions is large

### PR DESCRIPTION
**Pull request by michaelmdelcavalcanti**

### CODE REVIEW

**Comment by michaelmdelcavalcanti** [comment]
ci:test:sf

**Comment by liferay-immersion** [comment]
ci:test:relevant

**Comment by michaelhashimoto** [comment]
ci:test:relevant

**Review by alinedoleron — APPROVED** [review]

**Comment by alinedoleron** [comment]
ci:forward

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
ci:forward

**Pull request closed without merging**
