### PR TITLE
LPS-158234 The caret icon in define permission page not changes when expanded or collapsed

### PR DESCRIPTION
**Pull request by vngoliveira**

### CODE REVIEW

**Comment by vngoliveira** [comment]
ci:test:sf

**Comment by vngoliveira** [comment]
ci:relevant

**Comment by vngoliveira** [comment]
ci:test:relevant

**Review by RafaelCRC — APPROVED** [review]
LGTM!

**Review by gislayne-vitorino — APPROVED** [review]
LGTM!

**Comment by rafaelpdemelo** [comment]
I Will close this PR. Send to US&M

**Pull request closed without merging**
