### PR TITLE
LPS-152301 Remove pixel displacements when hovering over web content fields

### PR DESCRIPTION
**Pull request by rafaelpdemelo**
Description: I fixed the "animation" when mouse hover web content fields in web content structure
link LPS: https://issues.liferay.com/browse/LPS-152301

### CODE REVIEW

**Comment by rafaelpdemelo** [comment]
ci:test:sf

**Comment by rafaelpdemelo** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
Hi @rafaelpdemelo. I've tested the PR and it fixed the pixel displacement of sidebar. On the ticket there's also a pixel issue on the fields inside the form builder on Web Content. Please could you check this video and try to fix this case? We can notice this when we add Select and Text fields. 

https://user-images.githubusercontent.com/26491796/179564178-5c1d40e6-9639-47ab-a5b8-9559263a95e8.mp4

Thanks!

**Comment by rafaelpdemelo** [comment]
ci:test:sf

**Comment by rafaelpdemelo** [comment]
ci:test:relevant

**Comment by rafaelpdemelo** [comment]
ci:test:relevant

**Comment by rafaelpdemelo** [comment]
ci:test:relevant

**Review by alinedoleron — APPROVED** [review]

**Comment by alinedoleron** [comment]
ci:forward

**Pull request closed without merging**
