### PR TITLE
LPS-145052 Entries in View Entries overrides page elements

### PR DESCRIPTION
**Pull request by rafaelpdemelo**

### CODE REVIEW

**Comment by rafaelpdemelo** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
Hello, @rafaelpdemelo, 
Long labels for long Multiple Selection field labels is still broken (see picture).  Please, could you add the `word-break: break-all;` for the class `lfr-ddm-legend` to fix it?

Thanks =)
multipleselection_long_label
.

**Review by alinedoleron — CHANGES_REQUESTED** [review]
Hello, @rafaelpdemelo. Good job!
There's just one place that you need to change.
Long labels for Multiple Selection field is still broken (see picture). Please, could you add the` word-break: break-all;` for the class `lfr-ddm-legend` of `FieldBase.scss` to fix it?

Thanks =
multipleselection_long_label
)

**Comment by rafaelpdemelo** [comment]
Hi @alinedoleron ! Thank you for the feedback. Regarding the label error, which is still broken, it belongs to another LPS that i will be leaving here. I look forward to your review.

[LPS-145049](https://issues.liferay.com/browse/LPS-145049)

**Review by alinedoleron — APPROVED** [review]

**Comment by alinedoleron** [comment]
ci:forward

**Pull request closed without merging**
