### PR TITLE
LPS-159054 - Getting the URL from the previous page

### PR DESCRIPTION
**Pull request by Gabriel422-hue**
Related Issue: https://issues.liferay.com/browse/LPS-159054

Hi! This PR, correct the problem of the "Back" button, where when activated it redirected the user to the Worflows Tasks page.
I just put the check to get the previous page. Doubts can call, thank you!

### CODE REVIEW

**Comment by Gabriel422-hue** [comment]
ci:test:sf

**Comment by Gabriel422-hue** [comment]
ci:test:relevant

**Comment by Gabriel422-hue** [comment]
ci:test:relevant

**Comment by naraandrade** [comment]
Just started reviewing :)

**Review by naraandrade — CHANGES_REQUESTED** [review]
Hi @Gabriel422-hue, your code works for the case described in the ticket, but it breaks when the user access the entry through My Workflow Tasks directly. Maybe you need to do a if-else to check when to use your new code and when to use the previous code.

**Comment by Gabriel422-hue** [comment]
ci:test:sf

**Comment by Gabriel422-hue** [comment]
ci:test:sf

**Comment by Gabriel422-hue** [comment]
ci:test:sf

**Comment by Gabriel422-hue** [comment]
ci:test:sf

**Comment by Gabriel422-hue** [comment]
ci:test:sf

**Pull request closed without merging**
