### PR TITLE
LPS-145267 When the user views the workflow via Workflow Tracker the workflow is not localized according to the user's language selection

### PR DESCRIPTION
**Pull request by michaelmdelcavalcanti**
[LPS-145267](https://issues.liferay.com/browse/LPS-145267)

### CODE REVIEW

**Comment by michaelmdelcavalcanti** [comment]
ci:test:sf

**Comment by michaelmdelcavalcanti** [comment]
ci:test:relevant

**Comment by naraandrade** [comment]
Just started reviewing :)

**Review by naraandrade — APPROVED** [review]

**Comment by naraandrade** [comment]
ci:forward

**Pull request closed without merging**
