### PR TITLE
LPS-140642 Position error in message after delete a Field Set linked with a process at Manage Field Sets page

### PR DESCRIPTION
**Pull request by WallaceRooger**

### CODE REVIEW

**Comment by WallaceRooger** [comment]
ci:test:sf

**Comment by WallaceRooger** [comment]
ci:test:relevant

**Comment by naraandrade** [comment]
Just started reviewing :)

**Review by naraandrade — APPROVED** [review]

**Comment by naraandrade** [comment]
Hi @WallaceRooger, great job on this pull request :) Thanks!

**Comment by naraandrade** [comment]
ci:forward

**Comment by naraandrade** [comment]
ci:stop

**Comment by naraandrade** [comment]
@WallaceRooger Please, add the LPS of the bug ticket in the commit message. We will not be able to forward the pull request without that.

**Comment by WallaceRooger** [comment]
@naraandrade done!

**Comment by naraandrade** [comment]
ci:test:sf

**Comment by naraandrade** [comment]
ci:forward

**Comment by WallaceRooger** [comment]
ci:test:relevant

**Review by naraandrade — APPROVED** [review]

**Comment by naraandrade** [comment]
ci:forward

**Pull request closed without merging**
