### PR TITLE
LPS-148866 Icons not vertically centered in sticker

### PR DESCRIPTION
**Pull request by M-IgorFranca**

### CODE REVIEW

**Comment by M-IgorFranca** [comment]
ci:test:sf

**Comment by M-IgorFranca** [comment]
ci:test:relevant

**Comment by M-IgorFranca** [comment]
ci:test:sf

**Comment by M-IgorFranca** [comment]
ci:test:relevant

**Comment by naraandrade** [comment]
Just started reviewing :)

**Review by naraandrade — CHANGES_REQUESTED** [review]
Hey @M-IgorFranca, good job with this solution :) I would like to ask you to just move this code to the `_app.scss` file, as this current file is exclusive of our legacy code and we intend to ignore it on the future. Thanks!

**Pull request closed without merging**
