### PR TITLE
LPS-151189 There is an larger margin in the Kaleo Designer informations revision history tab

### PR DESCRIPTION
**Pull request by alberttgomes**

### CODE REVIEW

**Comment by alberttgomes** [comment]
ci:test:sf

**Comment by alberttgomes** [comment]
ci:test:relevant

**Comment by alberttgomes** [comment]
ci:test:sf

**Comment by alberttgomes** [comment]
ci:test:relevant

**Review by MariMalta — COMMENTED** [review]
Heyy @alberttgomes  your commit message should be describing what you did in the fix,  maybe something like 'LPS-xxxx fix margin in the Kaleo Design information revision history tab'. Could you please change that? Thanks! =)

**Comment by MariMalta** [comment]
Just started reviewing :)

**Comment by MariMalta** [comment]
Hi  again @alberttgomes,
I'll be approving this  pr, but there are some differences between the current version and the mockup, I know it's not in the ticket but there's a line under Details and Revision History that doesn't currently exist, also there is a margin in the version names and icon that doesn't currently exist. Next time feel free to correct and talk to qa about the ticket. Thanks!

**Review by MariMalta — APPROVED** [review]

**Comment by alberttgomes** [comment]
Hi @MariMalta,
Just follow what  was being requested in the ticket, bu, thank you advise.
Thanks!!!!

**Comment by alberttgomes** [comment]
> Heyy @alberttgomes  your commit message should be describing what you did in the fix,  maybe something like 'LPS-xxxx fix margin in the Kaleo Design information revision history tab'. Could you please change that? Thanks! =)

Ok @MariMalta thank you!!

**Pull request closed without merging**
