### PR TITLE
LPS-158113 Entries on the Relationship tab are deleted when clicking on it

### PR DESCRIPTION
**Pull request by JMachado98**
**Related issue:** https://issues.liferay.com/browse/LPS-158113

### CODE REVIEW

**Comment by JMachado98** [comment]
ci:test:sf

**Comment by JMachado98** [comment]
ci:test:relevant

**Comment by JMachado98** [comment]
ci:test:relevant

**Comment by JMachado98** [comment]
ci:test:relevant

**Comment by p-albuquerque** [comment]
resent [here](https://github.com/liferay-objects/liferay-portal/pull/901)

**Pull request closed without merging**
