### PR TITLE
LPS-163891 add validation to Object Field to show error when published with empty field

### PR DESCRIPTION
**Pull request by manuelecastro**
LINK LPS: https://issues.liferay.com/browse/LPS-163891

### CODE REVIEW

**Comment by manuelecastro** [comment]
ci:test:sf

**Comment by rafaelpdemelo** [comment]
ci:test:relevant

**Review by rafaelpdemelo — COMMENTED** [review]
LGTM ;)

**Review by rafaelpdemelo — APPROVED** [review]
LGTM! ;)

**Pull request closed without merging**
