### PR TITLE
LPS-140237 Required alert is displayed on Name and Label fields when only Label field is blank for Object and Object Field

### PR DESCRIPTION
**Pull request by MrJohn1911**

### CODE REVIEW

**Comment by MrJohn1911** [comment]
ci:test:sf

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Review by mateussgn — APPROVED** [review]

**Comment by mateussgn** [comment]
LGTM! 🎉

**Pull request closed without merging**
