### PR TITLE
LPS-144105 - Partial Results warning message is not aligned on Entries tab of form builder

### PR DESCRIPTION
**Pull request by alberttgomes**
Description: I correct the warning message removed the padding space.
link LPS: https://issues.liferay.com/browse/LPS-144105

### CODE REVIEW

**Comment by alberttgomes** [comment]
ci:test:sf

**Comment by alberttgomes** [comment]
ci:test:sf

**Comment by alinedoleron** [comment]
Hi @alberttgomes ! Actually, the problem of this ticket is that the messages are being displayed above the Entries bar. It's a limitation we have for now, as the messages are being mounted on jsp and the Reports is in React. So this issue is happening in other situations. See attachment:
messages
It will require a big refactoring on the code, so for now I think we could let this issue in stand by.
I'll close this pr ok?

**Comment by alberttgomes** [comment]
> 

Thanks yours analytics Aline! all right!!

**Pull request closed without merging**
