### PR TITLE
LPS-140461 - The long title of the page is overlaying the published form #21

### PR DESCRIPTION
**Pull request by Gabriel422-hue**

### CODE REVIEW

**Comment by Gabriel422-hue** [comment]
ci:test:sf

**Comment by Gabriel422-hue** [comment]
ci:test:relevant

**Comment by Gabriel422-hue** [comment]
ci:test:relevant

**Comment by Gabriel422-hue** [comment]
ci:test:relevant

**Review by alinedoleron — APPROVED** [review]

**Comment by alinedoleron** [comment]
ci:forward

**Pull request closed without merging**
