### PR TITLE
LPS-152741 - Added specific error message when admin tries to set a big folder name for Docs and Media attachment path

### PR DESCRIPTION
**Pull request by thiago-buarqque**
Related to issue: https://issues.liferay.com/browse/LPS-152741

The new objectFieldSetting value field length on database was changed to 255 by Daniel Angotti.

### CODE REVIEW

**Comment by thiago-buarqque** [comment]
ci:test:sf

**Comment by thiago-buarqque** [comment]
ci:test:relevant

**Comment by mateussgn** [comment]
Hey @thiago-buarqque, sorry for the delayed response.
Please, take a look at the comments on this PR: https://github.com/liferay-immersion/liferay-portal/pull/109
@danvb112 had reviewed the same ticket.

**Comment by mateussgn** [comment]
I'll close this PR since it is already reviewd.

**Comment by mateussgn** [comment]
ci:close

**Comment by mateussgn** [comment]
ci:reopen

**Comment by mateussgn** [comment]
LGTM! 🎉

**Comment by mateussgn** [comment]
ci:forward

**Pull request closed without merging**
