### PR TITLE
LPS-147642 The priority field tootltip inside actions in a node has the wrong value

### PR DESCRIPTION
**Pull request by michaelmdelcavalcanti**

### CODE REVIEW

**Comment by michaelmdelcavalcanti** [comment]
https://issues.liferay.com/browse/LPS-147642

**Comment by michaelmdelcavalcanti** [comment]
ci:test:sf

**Comment by michaelmdelcavalcanti** [comment]
ci:test:sf

**Comment by michaelmdelcavalcanti** [comment]
ci:test:relevant

**Comment by michaelmdelcavalcanti** [comment]
ci:test:relevant

**Comment by michaelmdelcavalcanti** [comment]
ci:test:relevant

**Comment by MariMalta** [comment]
Just started reviewing :)

**Review by MariMalta — APPROVED** [review]
Good job :)

**Comment by MariMalta** [comment]
ci:forward

**Pull request closed without merging**
