### PR TITLE
LPS-152295

### PR DESCRIPTION
**Pull request by AlmirFe**
https://issues.liferay.com/browse/LPS-152295
I have added a new useEffect in the component "WizardVariant.es.js" for scroll up when changing pages in forms

### CODE REVIEW

**Comment by AlmirFe** [comment]
ci:test:sf

**Comment by rafaelpdemelo** [comment]
ci:test:sf

**Comment by AlmirFe** [comment]
ci:test:sf

**Comment by AlmirFe** [comment]
ci:test:relevant

**Comment by AlmirFe** [comment]
ci:test:relevant

**Review by alinedoleron — APPROVED** [review]

**Comment by alinedoleron** [comment]
ci:forward

**Pull request closed without merging**
