### PR TITLE
LPS-148485 Correcting the Notification Types field

### PR DESCRIPTION
**Pull request by GabrielHenriquedev**
Hello reviewer, this PR seeks to fix the following [LPS](https://issues.liferay.com/browse/LPS-148485).

The solution was to initialize a variable as null and interact according to the user's choices.

### CODE REVIEW

**Comment by GabrielHenriquedev** [comment]
ci:test:sf

**Comment by GabrielHenriquedev** [comment]
ci:test:relevant

**Comment by GabrielHenriquedev** [comment]
ci:test:relevant

**Comment by GabrielHenriquedev** [comment]
ci:test:relevant

**Comment by naraandrade** [comment]
Just started reviewing :)

**Review by naraandrade — APPROVED** [review]

**Pull request closed without merging**
