### PR TITLE
LPS-157247 Create key lang  Custom Aggregation Field

### PR DESCRIPTION
**Pull request by GabrielHenriquedev**
Hello reviewer,
in this Pull Request I try to solve the following bug [LPS-157247](https://issues.liferay.com/browse/LPS-157247)

my solution was to just create the key for the language and do the build.

### CODE REVIEW

**Comment by GabrielHenriquedev** [comment]
ci:test:sf

**Comment by GabrielHenriquedev** [comment]
ci:test:relevant

**Comment by GabrielHenriquedev** [comment]
ci:test:relevant

**Review by danvb112 — APPROVED** [review]
LGTM! :tada:

**Comment by danvb112** [comment]
ci:forward

**Pull request closed without merging**
