### PR TITLE
LPS-79818 Predefined Values in Data and Color Fields can't be removed SF

### PR DESCRIPTION
**Pull request by HenriquePereiraa**

### CODE REVIEW

**Comment by HenriquePereiraa** [comment]
ci:test:sf

**Comment by HenriquePereiraa** [comment]
ci:test:relevant

**Comment by HenriquePereiraa** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
Hi @HenriquePereiraa. I've tested the solution and it solves the case for ColorField but it doesn't seem to solve the Date field issue. Actually, I cannot see any solution for that because the user can't select an empty data. I'll talk to the team to see if I pass this PR just for color field and then the guys can open a specific ticket for Date field.

**Comment by HenriquePereiraa** [comment]
Hi @alinedoleron, About the date bug, I talked to Pedro Michel and Mariana Malta and we came to the conclusion that it could be a feature request and not a bug

**Comment by alinedoleron** [comment]
Thanks for the update, @HenriquePereiraa! I'll forward the PR.

**Comment by alinedoleron** [comment]
ci:forward

**Review by alinedoleron — APPROVED** [review]

**Pull request closed without merging**
