### PR TITLE
LPS-153825 centered nodes in storyboard when the user goes back to Diagram View

### PR DESCRIPTION
**Pull request by felipelorenz**

### CODE REVIEW

**Comment by felipelorenz** [comment]
ci:test:sf

**Comment by felipelorenz** [comment]
ci:test:sf

**Comment by felipelorenz** [comment]
ci:test:relevant

**Comment by felipelorenz** [comment]
ci:test:relevant

**Comment by naraandrade** [comment]
Just started reviewing :)

**Review by naraandrade — APPROVED** [review]

**Comment by naraandrade** [comment]
ci:forward

**Pull request closed without merging**
