### PR TITLE
LPS-139478 - There is no warning message when resetting a page that has fields being used in a rule

### PR DESCRIPTION
**Pull request by alberttgomes**
I create new file to check if fields with rules applied when page reset.
And new language to modal Page Reset.
link LPS: https://issues.liferay.com/browse/LPS-139478

### CODE REVIEW

**Comment by alberttgomes** [comment]
ci:test:sf

**Comment by alberttgomes** [comment]
ci:test:relevant

**Comment by alberttgomes** [comment]
ci:test:relevant

**Comment by alberttgomes** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
ci:stop

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
ci:stop

**Comment by alinedoleron** [comment]
ci:test:sf

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by alberttgomes** [comment]
ci:test:sf

**Comment by alberttgomes** [comment]
ci:test:relevant

**Comment by alberttgomes** [comment]
ci:test:relevant

**Comment by alberttgomes** [comment]
ci:test:stop

**Comment by alberttgomes** [comment]
ci:test:relevant

**Comment by alberttgomes** [comment]
ci:stop

**Comment by alberttgomes** [comment]
ci:test:relevant

**Comment by alberttgomes** [comment]
ci:test:relevant

**Comment by alberttgomes** [comment]
ci:stop

**Pull request closed without merging**
