### PR TITLE
LPS-158283 Add Language Key

### PR DESCRIPTION
**Pull request by JMachado98**
**Related issue:** https://issues.liferay.com/browse/LPS-158283

### CODE REVIEW

**Comment by JMachado98** [comment]
ci:test:sf

**Comment by JMachado98** [comment]
ci:test:relevant

**Comment by JMachado98** [comment]
ci:test:relevant

**Comment by JMachado98** [comment]
> Hey @JMachado98, could you please resolve the conflicts? It's probably the `buildlang` commit causing the conflicts, so you can drop it, rebase the branch and then run buildlang again

Hey @danvb112, Done!

**Comment by danvb112** [comment]
Hey @JMachado98, the conflicts are still here, drop your buildlang commit again, and then you have to rebase your branch with the upstream master: `git pull --rebase upstream master` and rerun `gw buildlang`

**Comment by JMachado98** [comment]
Hey @danvb112, fixed! Can you check if still any conflicts?

**Review by danvb112 — APPROVED** [review]
LGTM! :tada:

**Comment by danvb112** [comment]
ci:forward

**Pull request closed without merging**
