### PR TITLE
LPS-155877 Add non-root context to BaseRole

### PR DESCRIPTION
**Pull request by M-IgorFranca**
https://issues.liferay.com/browse/LPS-155877

### CODE REVIEW

**Comment by M-IgorFranca** [comment]
ci:test:sf

**Comment by M-IgorFranca** [comment]
ci:test:relevant

**Comment by M-IgorFranca** [comment]
ci:test:sf

**Comment by M-IgorFranca** [comment]
ci:test:relevant

**Comment by naraandrade** [comment]
Just started reviewing :)

**Review by naraandrade — CHANGES_REQUESTED** [review]
@M-IgorFranca As you mentioned in the ticket, we have indeed other places presenting the same issue. Could you please move the `contextUrl` to the file `constants.js` inside the `definition-builder` folder and apply the same approach for the Recipient Types User and Role Type? The modification you made for Role fixed the problem for Role in Assignments, Notifications and Timers. Great job :)

**Comment by M-IgorFranca** [comment]
ci:test:sf

**Review by naraandrade — APPROVED** [review]

**Comment by naraandrade** [comment]
ci:test:relevant

**Comment by naraandrade** [comment]
ci:forward

**Pull request closed without merging**
