### PR TITLE
LPS-145839 Do not close the modal if there is an error

### PR DESCRIPTION
**Pull request by murilostodolni**
Related Issue: [LPS-145839](https://issues.liferay.com/browse/LPS-145839)

This PR has a fix to resolve problem with modal in Object. When an error there is in import json, the modal should not be close. The problem is in the reload the import_object_definiton.jsp and the flag visible is set false for default. For resolve the problem, a flag is create in the .jsp to verify if error exist.

### CODE REVIEW

**Comment by murilostodolni** [comment]
ci:test:sf

**Comment by murilostodolni** [comment]
ci:test:relevant

**Review by danvb112 — CHANGES_REQUESTED** [review]
Hey @murilostodoln, I don't think this is the best solution to this problem, we have a pattern in Objects which is to use the `onSubmit` of the form passing a function that does a `fetch`, so we can get the status of the response, so if the status is not ok you keep the modal open

Come to see me and I explain to you better :wink:

**Comment by murilostodolni** [comment]
Sent to: https://github.com/liferay-immersion/liferay-portal/pull/84

**Pull request closed without merging**
