### PR TITLE
LPS-155904 The portrait preview image displays too big for account

### PR DESCRIPTION
**Pull request by MrJohn1911**
Issue: https://issues.liferay.com/browse/LPS-155904

### CODE REVIEW

**Comment by MrJohn1911** [comment]
ci:test:sf

**Comment by MrJohn1911** [comment]
ci:test:sf

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Review by RafaelCRC — CHANGES_REQUESTED** [review]
Hi @MrJohn1911, please note that this tag changes preview images globally and the size isn't quite right. I suggest you to base yourself on the preview image of account users.

**Comment by RafaelCRC** [comment]
@MrJohn1911 when you finish this please assign the ticket to me clicking request review so we can merge this quickly :)

**Comment by RafaelCRC** [comment]
@drewbrokke i don't think there is a way to locally fix this, the source of the image is very large, the only thing to notice here is that the correct image size is 100px by 100px... do you have any suggestions?

**Pull request closed without merging**
