### PR TITLE
LPS-151047 The Role Name dropdown it's blank when a Account option is selected

### PR DESCRIPTION
**Pull request by RenanUmV**

### CODE REVIEW

**Comment by RenanUmV** [comment]
ci:test:sf

**Comment by RenanUmV** [comment]
ci:test:sf

**Comment by RenanUmV** [comment]
ci:test:relevant

**Comment by M-IgorFranca** [comment]
ci:test:relevant

**Comment by MariMalta** [comment]
Just started reviewing :)

**Review by MariMalta — APPROVED** [review]
Good job :)

**Review by MariMalta — APPROVED** [review]

**Comment by MariMalta** [comment]
ci:forward
ci:forward

**Pull request closed without merging**
