### PR TITLE
LPS-152741 - Added specific error message when admin tries to set a big folder name for Docs and Media attachment path

### PR DESCRIPTION
**Pull request by thiago-buarqque**
Related to issue: https://issues.liferay.com/browse/LPS-152741

### CODE REVIEW

**Comment by mateussgn** [comment]
LGTM! 🎉

**Comment by mateussgn** [comment]
ci:forward

**Comment by mateussgn** [comment]
ci:reevaluate:1367401_1648

**Comment by mateussgn** [comment]
ci:forward

**Comment by thiago-buarqque** [comment]
ci:test:sf

**Comment by thiago-buarqque** [comment]
ci:test:relevant

**Comment by mateussgn** [comment]
ci:forward

**Pull request closed without merging**
