### PR TITLE
LPS-156233 The user cannot delete a block in object layout

### PR DESCRIPTION
**Pull request by daiazius**
Related issue: https://issues.liferay.com/browse/LPS-156233

### CODE REVIEW

**Comment by daiazius** [comment]
ci:test:sf

**Comment by daiazius** [comment]
ci:test:relevant

**Review by danvb112 — APPROVED** [review]
LGTM! :tada: 

Good job on that @daiazius :wink:

**Comment by danvb112** [comment]
ci:forward

**Pull request closed without merging**
