### PR TITLE
LPS-151046 The Role Name dropdown not reset when another option is selected

### PR DESCRIPTION
**Pull request by MrJohn1911**

### CODE REVIEW

**Comment by MrJohn1911** [comment]
ci:test:sf

**Comment by MrJohn1911** [comment]
ci:test:sf

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by MariMalta** [comment]
Just started reviewing :)

**Review by MariMalta — APPROVED** [review]
Good job! :)

**Comment by MariMalta** [comment]
ci:forward

**Pull request closed without merging**
