### PR TITLE
LPS-153744 Timers Name it's not saved when field is filled

### PR DESCRIPTION
**Pull request by alberttgomes**
Link LPS: https://issues.liferay.com/browse/LPS-153744
Changed State and condition of useEffect, to correct time name and description field.

### CODE REVIEW

**Comment by alberttgomes** [comment]
ci:test:relevant

**Comment by MariMalta** [comment]
Just started reviewing :)

**Review by MariMalta — CHANGES_REQUESTED** [review]
Hey @alberttgomes Could you check if this bug is still happening? I tested here on my master without your changes  and I couldn't reproduce the bug. Thank you! :)

**Comment by alberttgomes** [comment]
> Hey @alberttgomes Could you check if this bug is still happening? I tested here on my master without your changes  and I couldn't reproduce the bug. Thank you! :)

Hi @MariMalta when i correct was happended. I will check! ;)

**Comment by alberttgomes** [comment]
In this case I had corrected two things, which was the state and the condition in useEffect, because there it is like "if(name && description)" but the description is not a mandatory field, if you put a name, exit and return it will persist, but if you delete the field, exit and return, it saves the first character. Could you see if this is happening? here on mine is.

**Comment by alberttgomes** [comment]
Hi @MariMalta the bug persist when you write  in just a field, name or description, they not mandatory.

**Comment by MariMalta** [comment]
Hii @alberttgomes that must have been what happened, I was writting both name and description. I'm going to test it again, together with the other problem that you said.  Thank you for helping me figure this out!

**Review by MariMalta — CHANGES_REQUESTED** [review]
Heyy @alberttgomes  I was testing here with your changes and found a problem. 

 I tried put name and description in the information area together with the mandatory fields and then got back to the sidebar. After that I got back to the created timer and tried to delete both name and description, when I got back to the timer the description was still filled. 
 
 Could you test that scenario in your computer? And if is really happening, could you try fix it? 
 
 Thank you!

**Comment by alberttgomes** [comment]
Hi @MariMalta i'm looking and think what found problem, think it is on variable updateSections, this variable return an array of name and description. I'm working to correct. Thanks!!

**Comment by alberttgomes** [comment]
Hi @MariMalta i'm looking and think what found problem, think it is on variable updateSections, this variable return an array of name and description. I'm working to correct. Thanks!!

**Comment by MariMalta** [comment]
Just started reviewing :)

**Comment by MariMalta** [comment]
ci:forward

**Pull request closed without merging**
