### PR TITLE
LPS-151042 Delete modal presents wrong visual effect at Kaleo Designer

### PR DESCRIPTION
**Pull request by rafaelpdemelo**

### CODE REVIEW

**Comment by rafaelpdemelo** [comment]
ci:test:sf

**Comment by rafaelpdemelo** [comment]
ci:test:sf

**Comment by rafaelpdemelo** [comment]
ci:help

**Comment by rafaelpdemelo** [comment]
ci:test:relevant

**Comment by cgmonte** [comment]
Just started reviewing :)

**Review by cgmonte — CHANGES_REQUESTED** [review]
Hey @rafaelpdemelo! It seems like you have modified a style from frontend-theme. This style is probably used by other modules from Liferay and modifying it will likely impact components from those modules as well. That would make sense if this bug was impacting other modules too, and then this PR should be sent to the team maintaining frontend-theme. For our specific case, I think you should keep modification inside `/modules/dxp/apps/portal-workflow/portal-workflow-kaleo-designer-web`, overwriting this style in this context.

**Comment by rafaelpdemelo** [comment]
Ok @cgmonte , I'll make the changes and send them again for you to take a look. Thx!

**Comment by rafaelpdemelo** [comment]
ci:test:sf

**Comment by rafaelpdemelo** [comment]
ci:test:relevant

**Comment by rafaelpdemelo** [comment]
ci:test:sf

**Comment by rafaelpdemelo** [comment]
ci:test:sf

**Comment by rafaelpdemelo** [comment]
@naraandrade I checked with @cgmonte and saw that the changes only really pick up the main.scss code that is out the way `src/main/resources/META-INF/resources/designer/css/definition-builder/` however, this file is legacy content. I'm waiting your review. Thx

**Comment by naraandrade** [comment]
Just started reviewing :)

**Review by naraandrade — APPROVED** [review]

**Pull request closed without merging**
