### PR TITLE
LPS-152651 Checkbox aligned according to text

### PR DESCRIPTION
**Pull request by WallaceRooger**

### CODE REVIEW

**Comment by WallaceRooger** [comment]
ci:test:sf

**Comment by WallaceRooger** [comment]
ci:test:relevant

**Comment by WallaceRooger** [comment]
ci:test:sf

**Comment by WallaceRooger** [comment]
ci:test:relevant

**Comment by MariMalta** [comment]
Just started reviewing :)

**Review by MariMalta — CHANGES_REQUESTED** [review]
Heyy @WallaceRooger. maybe we can do something a little more simple, what if we added

`.form-builder-field-node {
		margin-right: 5px;
		display: inline;
	}`
	
inside the existent .form-builder-field? What do you think? Do you think that would work? Could you please test that? Thank you!!!

**Comment by WallaceRooger** [comment]
@MariMalta  done!

**Comment by MariMalta** [comment]
Just started reviewing :)

**Review by MariMalta — APPROVED** [review]
Good job :)

**Comment by MariMalta** [comment]
ci:forward

**Comment by MariMalta** [comment]
@WallaceRooger Can you fix the SF problem please? Thanks

**Comment by WallaceRooger** [comment]
ci:test:sf

**Comment by MariMalta** [comment]
ci:forward

**Pull request closed without merging**
