### PR TITLE
LPS-158020 Workflow Status label is not displayed when user creates a field called Status

### PR DESCRIPTION
**Pull request by daiazius**
Related issue: https://issues.liferay.com/browse/LPS-158020

### CODE REVIEW

**Comment by daiazius** [comment]
ci:test:sf

**Comment by daiazius** [comment]
ci:test:relevant

**Comment by daiazius** [comment]
ci:test:relevant

**Comment by daiazius** [comment]
ci:test:relevant

**Comment by mateussgn** [comment]
LGTM! 🎉

**Comment by mateussgn** [comment]
ci:forward

**Pull request closed without merging**
