### PR TITLE
LPS-90833 fixed the bug by creating a new class for the label tag and adding a css rule

### PR DESCRIPTION
**Pull request by devpedrotavares**

### CODE REVIEW

**Comment by devpedrotavares** [comment]
ci:test:sf

**Comment by devpedrotavares** [comment]
ci:test:cancel

**Comment by devpedrotavares** [comment]
ci:help

**Comment by devpedrotavares** [comment]
ci:stop:sf

**Comment by devpedrotavares** [comment]
ci:stop

**Comment by devpedrotavares** [comment]
ci:test:sf

**Comment by pedro-michel** [comment]
Hey @devpedrotavares , can we close this PR?

**Comment by devpedrotavares** [comment]
> Hey @devpedrotavares , can we close this PR?

Yes!

**Pull request closed without merging**
