### PR TITLE
LPS-151435 Add HTML escape function

### PR DESCRIPTION
**Pull request by HenriquePereiraa**
add HTML escape function to keep the characters passed in the tag content unchanged. And in UpperToolbar add setDefinitionName so that the tag persists in the xml after updating

### CODE REVIEW

**Comment by HenriquePereiraa** [comment]
ci:test:sf

**Comment by HenriquePereiraa** [comment]
ci:test:relevant

**Comment by HenriquePereiraa** [comment]
ci:test:relevant

**Comment by naraandrade** [comment]
Just started reviewing :)

**Review by naraandrade — CHANGES_REQUESTED** [review]
@HenriquePereiraa you should apply the escape function in the content of all tags (excluding just the metadata and script tags, because we already "treat" them). That way you can avoid this bug in other tags, not only in the example given in the ticket.

**Comment by HenriquePereiraa** [comment]
> @HenriquePereiraa you should apply the escape function in the content of all tags (excluding just the metadata and script tags, because we already "treat" them). That way you can avoid this bug in other tags, not only in the example given in the ticket.

Ok, I'll implement it for the other cases

**Comment by HenriquePereiraa** [comment]
ci:test:sf

**Comment by HenriquePereiraa** [comment]
ci:test:relevant

**Comment by naraandrade** [comment]
Just started reviewing :)

**Comment by naraandrade** [comment]
Just started reviewing :)

**Comment by naraandrade** [comment]
ci:test:sf

**Comment by naraandrade** [comment]
ci:test:relevant

**Review by naraandrade — APPROVED** [review]

**Comment by naraandrade** [comment]
ci:forward

**Pull request closed without merging**
