### PR TITLE
LPS-152749 Fixing page styling implementation

### PR DESCRIPTION
**Pull request by lazhcsilva**
Related Issue: https://issues.liferay.com/browse/LPS-152749

Hello Reviewer!

The solution I found to resolve this bug throws some !important, as Clay is overriding all properties created for the page.
It was trying to insert ID's and new classes to try to impose the CSS edits on the page as a priority, but with no effect.

### CODE REVIEW

**Comment by lazhcsilva** [comment]
ci:test:sf

**Comment by lazhcsilva** [comment]
ci:test:sf

**Comment by lazhcsilva** [comment]
ci:test:sf

**Comment by lazhcsilva** [comment]
ci:test:relevant

**Review by alinedoleron — COMMENTED** [review]
Hello, @lazhcsilva =)
I was trying to identify the root case of this issue. It's not a good practice using **!important** attribute since it can cause problems even worse to find. 
What I've found is that on master, Clay have added a cadmin class that overrides a lot of content but it's not desirable for modal. I added a question on #t-dxp-frontend-infra channel and they answered a few minutes ago.

**Comment by alinedoleron** [comment]
Hi @lazhcsilva, please, undo the css changes and add this attribute `iframeBodyCssClass: ''` before the `onSelect` property on **_EditRecordSetStructureSelector.js_** file, so the 'cadmin' class will be removed. 

Like this:
```
if (openRecordSetModalButton) {
		openRecordSetModalButton.addEventListener('click', () => {
			const openerWindow = Liferay.Util.getOpener();

			openerWindow.Liferay.Util.openSelectionModal({
				iframeBodyCssClass: '',
				onSelect: (selectedItem) => {
					const form = document.getElementById(
						`${portletNamespace}fm`
					);

					if (!form) {
						return;
					}

					Liferay.Util.setFormValues(form, {
						ddmStructureId: selectedItem.ddmstructureid,
						ddmStructureNameDisplay: Liferay.Util.unescape(
							selectedItem.name
						),
					});
				},
				selectEventName,
				title: Liferay.Language.get('data-definitions'),
				url: itemSelectorURL,
			});
		});
	}
```

**Comment by lazhcsilva** [comment]
Thx @alinedoleron I'm checking the changes

**Comment by lazhcsilva** [comment]
ci:test:sf

**Comment by orsolyaDekany** [comment]
Hi @alinedoleron, I would need this fix as a solution for a customer's issue, could you please review the PR? Appreciate your help. Thank you.

**Comment by lazhcsilva** [comment]
ci:test:sf

**Comment by lazhcsilva** [comment]
ci:test:sf

**Comment by lazhcsilva** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
ci:forward

**Comment by lazhcsilva** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
ci:forward

**Pull request closed without merging**
